# This file is generated by https://github.com:pylover/python-makelib
import os.path
import re

from setuptools import setup, find_packages


# reading package's version (same way sqlalchemy does)
with open(
    os.path.join(os.path.dirname(__file__), 'poaitran', '__init__.py')
) as v_file:
    package_version = \
        re.compile('.*__version__ = \'(.*?)\'', re.S) \
        .match(v_file.read()) \
        .group(1)


dependencies = [
    'easycli',
    'openai',
]


setup(
    name='poaitran',
    version=package_version,
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    install_requires=dependencies,
    packages=find_packages(
        where='.',
        include=['poaitran'],
        exclude=['tests']
    ),
    entry_points={
        'console_scripts': [
            'poaitran = poaitran.cli:Main.quickstart'
        ]
    },
    classifiers=[
        'Environment :: Console',
        'Intended Audience :: Developers',
        'Natural Language :: English',
        'Development Status :: 5 - Production/Stable',
        'License :: Other/Proprietary License',
        'Operating System :: OS Independent',
        'Programming Language :: Python :: 3.12',
        'Programming Language :: Python :: 3.13',
        'Topic :: Software Development',
        'Topic :: Software Development :: Libraries',
        'Topic :: Software Development :: Libraries :: Python Modules',
    ]
)
